---
name: publish-pdfs
on:                             # yamllint disable-line rule:truthy
  push:
    branch:
      - release
jobs:
  publish-pdfs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a "v${{ github.run_number }}" -m "Release v${{ github.run_number }}"
          git push origin "v${{ github.run_number }}"
      - uses: xu-cheng/latex-action@v4
        with:
          root_file: |
            nanda-poster.tex
            nanda-syllabus-baseline.tex
            nanda-syllabus-revised.tex
          texlive_version: 2024
      - uses: softprops/action-gh-release@v2
        with:
          name: PDFs
          files: |
            nanda-poster.pdf
            nanda-syllabus-baseline.pdf
            nanda-syllabus-revised.pdf
